// This file was auto-generated by ML.NET Model Builder. 

using System;
using PTSchoolML.Model;

namespace PTSchoolML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                StudentId = @"4CCC49B1-EDEE-481D-011F-08D8989E9B88",
                ClubId = @"6C9CC020-5E7A-44D0-3A91-08D89C14F3DD",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Score with predicted Score from sample data...\n\n");
            Console.WriteLine($"StudentId: {sampleData.StudentId}");
            Console.WriteLine($"ClubId: {sampleData.ClubId}");
            Console.WriteLine($"\n\nPredicted Score: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
